# Generated by Django 2.0.2 on 2018-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('account', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=42)),
            ],
        ),
    ]
